version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: daksh
      POSTGRES_DB: UltimateTopicList
      POSTGRES_PASSWORD: test1234
    volumes:
      - pgdata:/var/lib/posgresql/data
    expose:
      - 5432
    ports:
      - 5432
  utl:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - . /app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: