# Generated by Django 3.2.8 on 2021-10-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20211030_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Category',
            new_name='category',
        ),
    ]
