# Generated by Django 3.2.9 on 2021-11-03 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_rename_category_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 19, 10, 12, 416072)),
        ),
    ]
