# Generated by Django 3.2.9 on 2021-11-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_alter_category_created_at'),
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='solved_topics',
            field=models.ManyToManyField(to='topics.Topic'),
        ),
    ]
